import { DISCOVER_BACKEND_URL } from "./discover-api";

export type TrustTier = "Bronze" | "Silver" | "Gold" | "Platinum";
export type DataSource = "live" | "mock" | "blended";

export interface TrustAnalysis {
  trustScore: number;
  tier: TrustTier;
  summary: string;
  strengths: string[];
  concerns: string[];
  recommendation: string;
  modelId: string;
  generatedAt: string;
  latencyMs: number;
  dataSource: DataSource;
  cached: boolean;
}

export type MarketTrend = "growing" | "stable" | "declining";
export type TrendStrength = "weak" | "moderate" | "strong";

export interface MarketAnalysis {
  trend: MarketTrend;
  trendStrength: TrendStrength;
  insight: string;
  forecast: string;
  opportunities: string[];
  buyerNote: string;
  /** Premium-only fields. Present when the analysis was generated by the
   *  paid x402 self-listing path (depth=premium). Optional so the free
   *  /api/listings/:id/market-analysis route still type-checks. */
  competitivePositioning?: string;
  pricingAnalysis?: string;
  riskFactors?: string[];
  actionPlan?: { thisWeek: string[]; thisMonth: string[] };
  modelId: string;
  generatedAt: string;
  latencyMs: number;
  dataSource: DataSource;
  cached: boolean;
}

export type AiAnalysisResult<T> =
  | { ok: true; data: T }
  | { ok: false; error: string };

async function fetchAi<T>(path: string): Promise<AiAnalysisResult<T>> {
  try {
    const res = await fetch(`${DISCOVER_BACKEND_URL}${path}`, { cache: "no-store" });
    if (!res.ok) {
      const body = (await res.json().catch(() => null)) as
        | { error?: { message?: string } | string }
        | null;
      const msg =
        typeof body?.error === "string"
          ? body.error
          : body?.error?.message ?? `HTTP ${res.status}`;
      return { ok: false, error: msg };
    }
    return { ok: true, data: (await res.json()) as T };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : String(e) };
  }
}

export function fetchTrustAnalysis(id: string): Promise<AiAnalysisResult<TrustAnalysis>> {
  return fetchAi<TrustAnalysis>(`/listings/${id}/trust-analysis`);
}

export function fetchMarketAnalysis(id: string): Promise<AiAnalysisResult<MarketAnalysis>> {
  return fetchAi<MarketAnalysis>(`/listings/${id}/market-analysis`);
}
