"use client";

import { useState } from "react";
import { useAccount } from "wagmi";
import { baseSepolia } from "@chain-lens/shared";
import { useMarketPayment } from "@/hooks/useMarketPayment";
import { MarketAnalysisView } from "@/components/discover/MarketAnalysisCard";
import type { MarketAnalysis } from "@/lib/ai-analysis-api";

/** ChainLens self-listing — registered on-chain, status APPROVED in DB.
 *  See docs: AI Market Analyst by ChainLens, payout=treasury, 0.5 USDC. */
const CHAINLENS_MARKET_ANALYST_LISTING_ID = "18";
const PRICE_ATOMIC = "500000"; // 0.5 USDC (6 decimals)

type Props = {
  /** The seller's own listing being analyzed. */
  targetListingId: number;
};

export default function BuyMarketAnalysisButton({ targetListingId }: Props) {
  const { isConnected } = useAccount();
  const { executePayment, step, error, isLoading } = useMarketPayment();
  const [analysis, setAnalysis] = useState<MarketAnalysis | null>(null);
  const [settleTx, setSettleTx] = useState<string | null>(null);
  const [localError, setLocalError] = useState<string | null>(null);

  async function handleBuy() {
    setLocalError(null);
    try {
      const res = await executePayment({
        listingId: CHAINLENS_MARKET_ANALYST_LISTING_ID,
        amount: PRICE_ATOMIC,
        inputs: { listingId: String(targetListingId) },
      });
      // The gateway wraps seller responses in { untrusted_data, ... }.
      const data = (res?.untrusted_data ?? null) as MarketAnalysis | null;
      if (!data || !data.trend) {
        setLocalError("Settlement succeeded but analysis payload was missing.");
      } else {
        setAnalysis(data);
        setSettleTx(res.settleTxHash ?? null);
      }
    } catch {
      // useMarketPayment exposes `error` already
    }
  }

  // If the buyer already has results, show them. Otherwise show the buy CTA.
  if (analysis) {
    return (
      <div className="mt-3">
        {settleTx && (
          <div className="mb-2 text-xs text-[var(--text3)]">
            Settled on-chain ·{" "}
            <a
              href={`${baseSepolia.blockExplorers.default.url}/tx/${settleTx}`}
              target="_blank"
              rel="noreferrer"
              className="font-mono text-[var(--accent)] underline underline-offset-2"
            >
              {settleTx.slice(0, 10)}…{settleTx.slice(-8)}
            </a>
          </div>
        )}
        <MarketAnalysisView analysis={analysis} omitBuyerNote />
      </div>
    );
  }

  return (
    <div className="mt-3 flex flex-col gap-2 rounded-lg border border-[var(--accent)] bg-[var(--accent-dim)] p-3 sm:flex-row sm:items-center sm:justify-between">
      <div className="min-w-0">
        <div className="flex items-center gap-2">
          <span className="rounded-full border border-[var(--accent)] px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.16em] text-[var(--accent)]">
            AI Market Analyst
          </span>
          <span className="text-[11px] uppercase tracking-[0.12em] text-[var(--text3)]">
            by ChainLens
          </span>
        </div>
        <p className="mt-1 text-xs text-[var(--text2)]">
          Fresh trend, forecast, and seller opportunities for this listing — generated by Claude on
          AWS Bedrock. Paid via x402 to ChainLens listing #{CHAINLENS_MARKET_ANALYST_LISTING_ID}.
        </p>
      </div>
      <button
        onClick={handleBuy}
        disabled={!isConnected || isLoading}
        className="btn-primary shrink-0 px-4 py-2 text-sm disabled:cursor-not-allowed disabled:opacity-60"
      >
        {step === "signing"
          ? "Sign…"
          : step === "submitting"
            ? "Generating…"
            : "Buy for 0.5 USDC"}
      </button>
      {(error || localError) && (
        <p className="basis-full text-xs text-[var(--red)] sm:basis-auto">
          {error || localError}
        </p>
      )}
    </div>
  );
}
