"use client";

import { useEffect, useState } from "react";
import { useAccount } from "wagmi";
import { baseSepolia } from "@chain-lens/shared";
import { useMarketPayment } from "@/hooks/useMarketPayment";
import {
  MarketAnalysisSkeleton,
  MarketAnalysisView,
} from "@/components/discover/MarketAnalysisCard";
import InlineSpinner from "@/components/shared/InlineSpinner";
import type { MarketAnalysis } from "@/lib/ai-analysis-api";

/** ChainLens self-listing — registered on-chain, status APPROVED in DB.
 *  See docs: AI Market Analyst by ChainLens, payout=treasury, 0.5 USDC. */
const CHAINLENS_MARKET_ANALYST_LISTING_ID = "18";
const PRICE_ATOMIC = "500000"; // 0.5 USDC (6 decimals)

type Props = {
  /** The seller's own listing being analyzed. */
  targetListingId: number;
};

export default function BuyMarketAnalysisButton({ targetListingId }: Props) {
  const { isConnected } = useAccount();
  const { executePayment, step, error, isLoading } = useMarketPayment();
  const [analysis, setAnalysis] = useState<MarketAnalysis | null>(null);
  const [settleTx, setSettleTx] = useState<string | null>(null);
  const [localError, setLocalError] = useState<string | null>(null);
  const [elapsed, setElapsed] = useState(0);

  // Tick an elapsed timer while loading so 25-40s waits don't read as "stuck"
  // — users can see progress is happening even though the button itself can't
  // expose Bedrock streaming progress.
  useEffect(() => {
    if (!isLoading) {
      setElapsed(0);
      return;
    }
    const start = Date.now();
    const interval = setInterval(() => {
      setElapsed(Math.floor((Date.now() - start) / 1000));
    }, 250);
    return () => clearInterval(interval);
  }, [isLoading]);

  async function handleBuy() {
    setLocalError(null);
    try {
      const res = await executePayment({
        listingId: CHAINLENS_MARKET_ANALYST_LISTING_ID,
        amount: PRICE_ATOMIC,
        inputs: { listingId: String(targetListingId) },
      });
      // The gateway wraps seller responses in { untrusted_data, ... }.
      const data = (res?.untrusted_data ?? null) as MarketAnalysis | null;
      if (!data || !data.trend) {
        setLocalError("Settlement succeeded but analysis payload was missing.");
      } else {
        setAnalysis(data);
        setSettleTx(res.settleTxHash ?? null);
      }
    } catch {
      // useMarketPayment exposes `error` already
    }
  }

  if (analysis) {
    return (
      <div className="mt-3 animate-fade-up">
        {settleTx && (
          <div className="mb-2 text-xs text-[var(--text3)] animate-fade-up">
            Settled on-chain ·{" "}
            <a
              href={`${baseSepolia.blockExplorers.default.url}/tx/${settleTx}`}
              target="_blank"
              rel="noreferrer"
              className="font-mono text-[var(--accent)] underline underline-offset-2"
            >
              {settleTx.slice(0, 10)}…{settleTx.slice(-8)}
            </a>
          </div>
        )}
        <div className="animate-fade-up-delayed">
          <MarketAnalysisView analysis={analysis} omitBuyerNote />
        </div>
      </div>
    );
  }

  // While the paid call is in flight, replace the static buy CTA with a
  // live progress card and a content skeleton so the seller sees that work
  // is happening.
  if (isLoading) {
    return (
      <div className="mt-3 space-y-3">
        <div className="rounded-lg border border-[var(--accent)] bg-[var(--accent-dim)] p-3">
          <div className="flex items-center gap-2 text-sm text-[var(--text)]">
            <InlineSpinner size={14} className="text-[var(--accent)]" />
            <strong>{stageLabel(step)}</strong>
            <span className="ml-auto font-mono text-xs text-[var(--text3)]">{elapsed}s</span>
          </div>
          <p className="mt-2 text-xs text-[var(--text2)]">{stageDetail(step)}</p>
          <ProgressTrack step={step} />
        </div>
        <MarketAnalysisSkeleton />
      </div>
    );
  }

  return (
    <div className="mt-3 flex flex-col gap-2 rounded-lg border border-[var(--accent)] bg-[var(--accent-dim)] p-3 sm:flex-row sm:items-center sm:justify-between">
      <div className="min-w-0">
        <div className="flex items-center gap-2">
          <span className="rounded-full border border-[var(--accent)] px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.16em] text-[var(--accent)]">
            AI Market Analyst
          </span>
          <span className="text-[11px] uppercase tracking-[0.12em] text-[var(--text3)]">
            by ChainLens
          </span>
        </div>
        <p className="mt-1 text-xs text-[var(--text2)]">
          Fresh trend, forecast, and seller opportunities for this listing — generated by Claude on
          AWS Bedrock. Paid via x402 to ChainLens listing #{CHAINLENS_MARKET_ANALYST_LISTING_ID}.
        </p>
      </div>
      <button
        onClick={handleBuy}
        disabled={!isConnected}
        className="btn-primary shrink-0 px-4 py-2 text-sm disabled:cursor-not-allowed disabled:opacity-60"
      >
        Buy for 0.5 USDC
      </button>
      {(error || localError) && (
        <p className="basis-full text-xs text-[var(--red)] sm:basis-auto">
          {error || localError}
        </p>
      )}
    </div>
  );
}

function stageLabel(step: string): string {
  switch (step) {
    case "signing":
      return "Sign USDC authorization in your wallet…";
    case "submitting":
      return "Generating premium analysis & settling on-chain…";
    default:
      return "Working…";
  }
}

function stageDetail(step: string): string {
  switch (step) {
    case "signing":
      return "Sign the EIP-3009 ReceiveWithAuthorization message — no transaction yet, just an authorization.";
    case "submitting":
      return "Gateway is invoking Claude on AWS Bedrock for the in-depth analysis (≈25-40s) and then submitting settle() on Base Sepolia.";
    default:
      return "";
  }
}

function ProgressTrack({ step }: { step: string }) {
  const stages: Array<{ key: string; label: string }> = [
    { key: "signing", label: "Sign" },
    { key: "submitting", label: "Generate + settle" },
    { key: "success", label: "Done" },
  ];
  const activeIdx = stages.findIndex((s) => s.key === step);
  return (
    <div className="mt-3 flex items-center gap-2 text-[10px] uppercase tracking-[0.12em] text-[var(--text3)]">
      {stages.map((s, i) => {
        const done = i < activeIdx;
        const active = i === activeIdx;
        return (
          <span
            key={s.key}
            className={`flex items-center gap-1 ${done ? "text-[var(--green)]" : active ? "text-[var(--accent)]" : ""}`}
          >
            <span
              className={`inline-block h-1.5 w-1.5 rounded-full ${
                done
                  ? "bg-[var(--green)]"
                  : active
                    ? "bg-[var(--accent)] animate-pulse"
                    : "bg-[var(--border2)]"
              }`}
            />
            {s.label}
            {i < stages.length - 1 && <span className="text-[var(--border2)]">·</span>}
          </span>
        );
      })}
    </div>
  );
}
